# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  node8:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/xxhash-addon

    steps:      
      - checkout
      - run: sudo apt-get install python g++ make
      - run: node --version
      - run: npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run ci:install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm install jest --save-dev
      - run: npm test

      # package and install
      - run: |
          npm pack
          mkdir ~/package_install
          cp xxhash-addon*.tgz ~/package_install
          cd ~/package_install
          npm install xxhash-addon*.tgz

  node10:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/xxhash-addon

    steps:      
      - checkout
      - run: sudo apt-get install python g++ make
      - run: node --version
      - run: npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run ci:install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm install jest --save-dev
      - run: npm test

      # package and install
      - run: |
          npm pack
          mkdir ~/package_install
          cp xxhash-addon*.tgz ~/package_install
          cd ~/package_install
          npm install xxhash-addon*.tgz

  node12:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/xxhash-addon

    steps:      
      - checkout
      - run: sudo apt-get install python g++ make
      - run: node --version
      - run: npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run ci:install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm install jest --save-dev
      - run: npm test

      # package and install
      - run: |
          npm pack
          mkdir ~/package_install
          cp xxhash-addon*.tgz ~/package_install
          cd ~/package_install
          npm install xxhash-addon*.tgz

  nodelatest:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/xxhash-addon

    steps:      
      - checkout
      - run: sudo apt-get install python g++ make
      - run: node --version
      - run: npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm run ci:install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm install jest --save-dev
      - run: npm test

      # package and install
      - run: |
          npm pack
          mkdir ~/package_install
          cp xxhash-addon*.tgz ~/package_install
          cd ~/package_install
          npm install xxhash-addon*.tgz

workflows:
  version: 2
  build_all:
    jobs:
      - node8:
          filters:
            branches:
              only:
                - master
      - node10:
          requires:
            - node8
          filters:
            branches:
              only:
                - master
      - node12:
          requires:
            - node10
          filters:
            branches:
              only:
                - master
      - nodelatest:
          requires:
            - node12
          filters:
            branches:
              only:
                - master